### ISSUE TITLE
Build Failed : taskdef class org.testng.TestNGAntTask cannot be found

### ISSUE THREAD

**Issue by QAInsights** [ycrash/buggyapp#2]
As the title says, when I try build the package, I am getting below error:

```
Buildfile: /home/osboxes/git/buggyapp/build.xml

BUILD FAILED
/home/osboxes/git/buggyapp/build.xml:70: taskdef class org.testng.TestNGAntTask cannot be found
 using the classloader AntClassLoader[]

Total time: 0 seconds
```

**Comment by mahesh-tier1app** [comment]
Hi,

The issue has been fixed. Please refer to the release [v1.0.0](https://github.com/ycrash/buggyapp/releases/tag/v1.0.0).

**Comment by QAInsights** [comment]
@mahesh-tier1app It is working now. Closing this issue. Thanks!
