### ISSUE TITLE
buggyapp.war file is missing

### ISSUE THREAD

**Issue by QAInsights** [ycrash/buggyapp#3]
In the latest release, `buggyapp.war` is missing in `embedded-runner` folder. Please check this issue.

**Comment by mahesh-tier1app** [comment]
Hi @QAInsights, ```embedded-runner``` folder will not have ```buggyApp.war ```.  You will need to build the buggyApp project to get the ```buggyApp.war``` file. Please follow the below steps:

1. Run ```ant clean``` command.
2. Run ```ant dist-ee``` command.
3. Now you will see ```dist``` folder in buggyApp project.
4. Go to the ```dist``` folder and unzip ```buggyapp-*.zip``` file.

For more information please go through the README.md file.

**Comment by QAInsights** [comment]
Sorry, I messed up with the previous release. Now I see it, closing this issue.
